
IF (WIN32)
	FIND_PATH(OPENCL_INCLUDE_DIR CL/cl.h )
	FIND_LIBRARY(OPENCL_LIBRARIES opencl64 )
	IF( OPENCL_LIBRARIES )
		FIND_LIBRARY(OPENCL_LIBRARIES opencl32 )
	ENDIF( OPENCL_LIBRARIES )
ELSE (WIN32)
	FIND_PATH(OPENCL_INCLUDE_DIR CL/cl.h ~/NVIDIA_GPU_Computing_SDK/OpenCL/common/inc/ )
	FIND_LIBRARY(OPENCL_LIBRARIES OpenCL 
	  ENV LD_LIBRARY_PATH
	)
ENDIF (WIN32)

SET( OPENCL_FOUND "NO" )
IF(OPENCL_LIBRARIES )
	SET( OPENCL_FOUND "YES" )
ENDIF(OPENCL_LIBRARIES)

MARK_AS_ADVANCED(
  OPENCL_INCLUDE_DIR
)


find_package(OpenCL REQUIRED )

include_directories( ${OPENCL_INCLUDE_DIR} )